out='/n/home11/spb/data/ComparisonProject/Arepo_128/'
base='/n/hernquistfs1/mvogelsberger/ComparisonProject/128_20Mpc/Arepo_ENERGY/output/'
gamma.read_gamma(124,base,out)
out='/n/home11/spb/data/ComparisonProject/Gadget_128/'
base='/n/hernquistfs1/mvogelsberger/ComparisonProject/128_20Mpc/Gadget/output/'
gamma.read_gamma(124,base,out)
out='/n/home11/spb/data/ComparisonProject/Arepo_256/'
base='/n/hernquistfs1/mvogelsberger/ComparisonProject/256_20Mpc/Arepo_ENERGY/output/'
gamma.read_gamma(124,base,out)
out='/n/home11/spb/data/ComparisonProject/Gadget_256/'
base='/n/hernquistfs1/mvogelsberger/ComparisonProject/256_20Mpc/Gadget/output/'
gamma.read_gamma(124,base,out)
out='/n/home11/spb/data/ComparisonProject/Arepo/'
base='/n/hernquistfs1/mvogelsberger/ComparisonProject/512_20Mpc/Arepo_ENERGY/output/'
gamma.read_gamma(124,base,out)
out='/n/home11/spb/data/ComparisonProject/Gadget/'
base='/n/hernquistfs1/mvogelsberger/ComparisonProject/512_20Mpc/Gadget/output/'
gamma.read_gamma(124,base,out)
